trigger: 
- main

pool: 
   name: agent01

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: agent01
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello Rock"
