trigger:
- main  # Adjust if your default branch is different

pool:
  name: 'agent01'

steps:
- script: |
    echo "Hello, World!" > helloworld.txt
  displayName: 'Create HelloWorld file'

- publish: helloworld.txt
  artifact: helloworld
  displayName: 'Publish HelloWorld Artifact'